### ISSUE TITLE
Unable to progress past 84/950

### ISSUE THREAD

**Issue by PAK90** [samirelanduk/reddit-save#10]
I tried running this app, but it always seems to get stuck at item number 84/950. Running in win10 in the cmd shell, using the command:
`py save.py upvoted target/folder`

Tried looking for logs for errors but didn't see any? I've been able to restart the process and immediately see it work again so I'm guessing it's not some sort of rate limiting.

**Comment by samirelanduk** [comment]
It can happen sometimes when the thing it's downloading is particularly large - hard to say without knowing what item 84 is. A log file might be helpful you're right, but I won't have time to add that for a while I'm afraid.

**Comment by PAK90** [comment]
It turns out that file was just very large and after I left it for a good while (30mins or so), it got past item 84.

**Comment by samirelanduk** [comment]
No problem - glad it was resolved
