### ISSUE TITLE
Touch doesn't work on Windows

### ISSUE THREAD

**Issue by bioluminesceme** [samirelanduk/reddit-save#3]
Manually create _secrets.py_ and add 

    REDDIT_USERNAME = "username"
    REDDIT_PASSWORD =  "password"
    REDDIT_CLIENT_ID = "shorterstring"
    REDDIT_SECRET = "longersecretstring"

(Maybe you can add this to the readme, not sure if it was worth a whole pull/merge request, script is running fine here! thanks!)

**Comment by samirelanduk** [comment]
Oh, good catch - I've updated the README. Thanks a lot.
