### ISSUE TITLE
Add Docker Info to README

### ISSUE THREAD

**Issue by darylf** [samirelanduk/reddit-save#4]
Hi, I just discovered this repository and it works splendidly! I was going to suggest docker-ifying the script, until I noticed you already had a dockerfile and docker-compose in the code.

You might want to consider adding instructions to the readme guiding how to to run the script as a docker container. It would have made some of the setup (albiet already quite simple) even easier.

Thanks for all your hard work!

**Comment by thisaccountname** [comment]
Wishing for the same thing right now @darylf 

What was your final compose process? I'm getting 

```
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

ERROR: pull access denied for reddit-save, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by samirelanduk** [comment]
Hi all, so I didn't do the Docker stuff, this was kindly contributed by another user - though I agree it would be the easiest way to get this set up.

I will look into this properly later, but in the meantime if you just delete the `image` line will it not just try to build it from the local Dockerfile? As far as I know there is no reddit-save image on Dockerhub.

**Comment by samirelanduk** [comment]
Just added some instructions now, let me know if anything still doesn't work.
