### ISSUE TITLE
Docker-compose usage instructions

### ISSUE THREAD

**Issue by Coo-ops** [samirelanduk/reddit-save#6]
Instructions on how to run this via docker compose would be appreicated,

I'm wanting to potentially create ad-hoc or scheduled archiving tasks but can't find a way to specify which command it should run.

Using the docker-compose.yml template with my details plugged into it.

```Successfully tagged saved:latest
Creating hld-reddit-save_reddit-save_1 ... done
Attaching to hld-reddit-save_reddit-save_1
reddit-save_1  | usage: save.py [-h] {saved,upvoted}
reddit-save_1  | save.py: error: the following arguments are required: mode
hld-reddit-save_reddit-save_1 exited with code 2```

**Comment by samirelanduk** [comment]
It should be the same command - `save.py saved /path/to/folder` to get saved content for example.
